# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}]

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0}]

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}]

# IP: bd/system/ip/system_axi_dynclk_0_0/system_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0_0 || ORIG_REF_NAME==system_axi_dynclk_0_0}]

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}]

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}]

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0}]

# IP: bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_subset_converter_0_0 || ORIG_REF_NAME==system_axis_subset_converter_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0}]

# IP: bd/system/ip/system_rst_processing_system7_0_140M_0/system_rst_processing_system7_0_140M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_140M_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0}]

# IP: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0}]

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}]

# IP: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_1 || ORIG_REF_NAME==system_axi_gpio_1_1}]

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1}]

# IP: bd/system/ip/system_alinx_ov5640_0_0/system_alinx_ov5640_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_alinx_ov5640_0_0 || ORIG_REF_NAME==system_alinx_ov5640_0_0}]

# IP: bd/system/ip/system_alinx_ov5640_0_0/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}]

# IP: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0}]

# IP: bd/system/ip/system_alinx_ov5640_0_1/system_alinx_ov5640_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_alinx_ov5640_0_1 || ORIG_REF_NAME==system_alinx_ov5640_0_1}]

# IP: bd/system/ip/system_alinx_ov5640_0_1/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}]

# IP: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_140M_0/system_rst_processing_system7_0_140M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_140M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_140M_0/system_rst_processing_system7_0_140M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_140M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_140M_0/system_rst_processing_system7_0_140M_0_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_1 || ORIG_REF_NAME==system_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_1 || ORIG_REF_NAME==system_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_alinx_ov5640_0_0/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_alinx_ov5640_0_0/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_alinx_ov5640_0_0/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_ooc.xdc

# XDC: bd/system/ip/system_alinx_ov5640_0_1/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_alinx_ov5640_0_1/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_alinx_ov5640_0_1/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/system/system_ooc.xdc
